---
- name: vim autoload directory
  file: path={{ home }}/.vim/autoload state=directory owner={{ username }} group={{ groupname }} mode=0755

- name: vim plug directory
  file: path={{ home }}/.vim/plug state=directory owner={{ username }} group={{ groupname }} mode=0755

- stat: path={{ home }}/.vim/autoload/plug.vim
  register: f
- name: install plug
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim
  when: not f.stat.exists

